config/routes.rb
VDocFlow::Application.routes.draw do
  resources :chat_rooms do
    member do
      post :post_message
      get :leave
    end
  end

  resources :docs do
    member do
      post :change_responsible
      post :to_review
      post :reject
      post :to_revision
      post :accept
      post :to_execution
      post :to_confirmation_of_execution
      post :to_executed
      get :create_chat_room
      get :print
    end
  end

  resources :doc_types do
    member do
      get 'get_lines'
    end
  end

  devise_for :users

  resources :users do
    member do
      get 'toggle_status'
    end
  end

  root :to => 'docs#index'

end

app/models/chat_room.rb
class ChatRoom
  include Mongoid::Document
  include Mongoid::Timestamps::Created::Short

  field :name
  field :doc_id, type: BSON::ObjectId, default: nil
  field :member_ids, type: Array, default: []
  belongs_to :user
  has_many :message_notifications
  embeds_many :messages

  validates_presence_of :name

  attr_reader :member_tokens

  def members
    member_ids.map{|id| User.find(id)}
  end

  def member_tokens=(ids)
    self.member_ids = ids.split(",")
  end

  def message_notifications_by_user(user)
    return message_notifications.select{|n| n.user == user}
  end

  def build_system_message(action, user, diff_users = [])
    message = case action
    when :create_room
      "Пользователь <strong>#{user.name}</strong> создал чат."
    when :rename_room
      "Пользователь <strong>#{user.name}</strong> изменил название чата.
      Новое название чата: <strong>#{name}</strong>"
    when :leave_room
      "Пользователь <strong>#{user.name}</strong> покинул чат."
    when :added_users
      "Пользователь <strong>#{user.name}</strong> добавил следующих пользователей в чат (#{diff_users.size}):\n"+
      diff_users.map{|u| u.name}.join("\n")
    when :deleted_users
      "Пользователь <strong>#{user.name}</strong> исключил следующих пользователей из чата (#{diff_users.size}):\n"+
      diff_users.map{|u| u.name}.join("\n")
    end
    s_m = messages.build(body: message)
    s_m.save
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :set_chat_room, only: [:show, :edit, :update, :destroy, :post_message, :leave]
  before_action :clean_notifications, only: [:show, :leave]
  before_action :check_owner_abilities, only: [:edit, :update, :destroy]
  before_action :check_member_abilities, only: [:show, :post_message]
  before_action :set_token_params, only: [:create, :update]

  def index
    @chat_rooms = ChatRoom.where(member_ids: current_user.id.to_s).sort_by{|c| (c.messages.last || c).send(:c_at)}.reverse

    @has_ntf = {}
    @chat_rooms.each do |c|
      @has_ntf[c.id] = !c.message_notifications_by_user(current_user).blank?
    end
  end

  def show

  end

  def new
    @chat_room = ChatRoom.new(member_ids:  [current_user.id.to_s])
  end

  def edit
  end

  def post_message
    message = @chat_room.messages.new(message_params)
    message.save
    redirect_to @chat_room
  end

  def leave
    if @chat_room.user == current_user
      redirect_to chat_rooms_path, alert: t('.cannot_leave_owner') and return
    elsif @chat_room.member_ids.include?(current_user.id.to_s)
      @chat_room.build_system_message(:leave_room, current_user)
      @chat_room.member_ids.delete(current_user.id.to_s)
      @chat_room.save
      redirect_to chat_rooms_path, notice: t('.successfully') and return
    else
      redirect_to chat_rooms_path, alert: t('.cannot_leave_not_member') and return
    end
  end

  def create
    @chat_room = ChatRoom.new(chat_room_params)
    @chat_room.member_ids = @member_ids

    if @chat_room.save
      @chat_room.build_system_message(:create_room, current_user)
      @chat_room.build_system_message(:added_users, current_user, @chat_room.members)
      redirect_to @chat_room, notice: 'Чат создан успешно.'
    else
      render action: 'new'
    end
  end

  def update
    if @member_ids.blank?
      flash.now[:alert] = t('cannot_be_blank')
      render action: 'edit'
      return
    end

    deleted_members = @chat_room.members - @members_after
    added_members = @members_after - @chat_room.members

    if @chat_room.update(chat_room_params)
      @chat_room.member_ids = @member_ids
      @chat_room.build_system_message(:added_users, current_user, added_members) unless added_members.blank?
      @chat_room.build_system_message(:deleted_users, current_user, deleted_members) unless deleted_members.blank?
      @chat_room.save
      redirect_to @chat_room, notice: 'Чат обновлен успешно.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @chat_room.destroy
    redirect_to chat_rooms_path, notice: 'Чат удален.'
  end

  private

  def set_chat_room
    @chat_room = ChatRoom.find(params[:id])
  end

  def clean_notifications
    @chat_room.message_notifications_by_user(current_user).each{|n| n.delete }
  end

  def check_owner_abilities
    redirect_to chat_rooms_path, alert: t('.not_chat_owner') and return unless
      @chat_room.user == current_user
  end

  def check_member_abilities
    redirect_to chat_rooms_path, alert: t('.not_chat_member') and return unless
      @chat_room.member_ids.include?(current_user.id.to_s)
  end

  def chat_room_params
    params.require(:chat_room).permit!
  end

  def message_params
    params.require(:message).permit!
  end

  def set_token_params
    @member_ids = (params[:chat_room][:member_tokens].split(',')).unshift(current_user.id.to_s).uniq
    @members_after = @member_ids.map{|m| User.find(m)}
  end
end

app/views/chat_rooms/_form.html.haml
= form_for @chat_room do |f|
  - if @chat_room.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chat_room.errors.count, "error")} prohibited this chat_room from being saved:"
      %ul
        - @chat_room.errors.full_messages.each do |msg|
          %li= msg
  .row
    .form-group.col-xs-9
      = f.label :name, nil, class: "col-xs-3 control-label"
      .col-xs-6
        = f.text_field :name, class: "form-control"

    .form-group.col-xs-9
      = f.label :member_tokens, "members", class: "col-xs-3 control-label"
      .col-xs-6
        = f.text_field :member_tokens, class: "form-control", "data-pre" => @chat_room.members.map(&:alt_attrs).to_json

  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :doc_id, value: params[:doc_id]
  .actions
    = f.submit t("save"), class: 'btn btn-success'

app/views/chat_rooms/_message.html.haml
.well.well-sm
  %span.label.label-info.label-bg
    = l message.c_at, format: :short
    = message.user.name
  %div= message.body.gsub("\n", "<br>").html_safe

app/views/chat_rooms/_message_form.html.haml
= form_for Message.new, url: post_message_chat_room_path, method: :post do |f|
  = f.text_area :body, class: "form-control"
  = f.hidden_field :user_id, value: current_user.id
  .actions
    = f.submit t("post_message"), class: 'btn btn-success'

app/views/chat_rooms/_system_message.html.haml
.well.well-sm
  %span.label.label-warning.label-bg
    = l message.c_at, format: :short
  %hr
  = message.body.gsub("\n", "<br>").html_safe

app/views/chat_rooms/edit.html.haml
%h1 Editing chat_room

= render 'form'

= link_to 'Show', @chat_room
\|
= link_to 'Back', chat_rooms_path

app/views/chat_rooms/index.html.haml
%h2= t(".title")
%br
%table.table.table-hover
  - @chat_rooms.each do |chat_room|
    %tr
      %td.col-md-1
        %span.glyphicon.glyphicon-envelope{class: @has_ntf[chat_room.id] ? "text-primary" : "" }
      %td.col-md-9
        = chat_room.name
      %td.col-md-2
        .btn-group
          = link_to t("show"), chat_room, class: "btn btn-default"
          %button.btn.btn-success.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li= link_to t("edit"), edit_chat_room_path(chat_room)
            %li.divider
            %li= link_to t("destroy"), chat_room, method: :delete, data: { confirm: t("confirm") }

= link_to new_chat_room_path, class: "btn btn-success" do
  %span.glyphicon.glyphicon-plus
  = t('chat_rooms.new_chat_room')

app/views/chat_rooms/new.html.haml
= link_to chat_rooms_path do
  %span.glyphicon.glyphicon-arrow-left
  Cпискок чатов

%h2 Новый чат
%hr
= render 'form'

app/views/chat_rooms/show.html.haml
.panel-group
  .panel.panel-default
    .panel-body
      -if @chat_room.doc_id
        = link_to doc_path(@chat_room.doc_id), title: ('.go_to_doc') do
          %span.glyphicon.glyphicon-book
      = @chat_room.name
      = link_to t(".leave"), leave_chat_room_path(@chat_room), class: "btn btn-primary"
      = link_to t("edit"), edit_chat_room_path(@chat_room), class: "btn btn-primary"
      = link_to t("back"), chat_rooms_path, class: "btn btn-primary"
      %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseOne", class: "pull-right", :title => t(".users")}
        %span.glyphicon.glyphicon-chevron-down
    #collapseOne.panel-collapse.collapse{class: "out"}
      .panel-footer
        - @chat_room.members.each do |member|
          %p= member.name


.messages
  - if @chat_room.messages.empty?
    %h4= t('.no_messages')
  - else
    - @chat_room.messages.each do |message|
      -if message.system_message?
        = render partial: "chat_rooms/system_message", locals: {message: message}
      -else
        = render partial: "chat_rooms/message", locals: {message: message}
%hr
= render "message_form"