config/routes.rb
VDocFlow::Application.routes.draw do
  resources :chat_rooms do
    member do
      post :post_message
      get :leave
    end
  end

  resources :docs do
    member do
      post :change_responsible
      post :to_review
      post :reject
      post :to_revision
      post :accept
      post :to_execution
      post :to_confirmation_of_execution
      post :to_executed
      get :create_chat_room
      get :print
    end
  end

  resources :doc_types do
    member do
      get 'get_lines'
    end
  end

  devise_for :users

  resources :users do
    member do
      get 'toggle_status'
    end
  end

  root :to => 'docs#index'

end

app/controllers/doc_types_controller.rb
class DocTypesController < ApplicationController

  before_filter :check_admin!, except: [:show, :get_lines]
  before_filter :set_doc_type, only: [:show, :edit, :update, :destroy, :get_lines]

  def index
    @doc_types = DocType.active
  end

  def show
  end

  def new
    @doc_type = DocType.new
    @doc_type.lines.build
  end

  def edit
  end

  def create
    @doc_type = DocType.new(doc_type_params)
    if @doc_type.save
      redirect_to @doc_type, notice: 'Тип документа успешно создан.'
    else
      render action: "new"
    end
  end

  def update
    # raise params.inspect
    if @doc_type.update_attributes(doc_type_params)
      @doc_type.print_settings = params[:print_settings] || {}
      @doc_type.save
      redirect_to @doc_type, notice: 'Тип документа успешно обновлен.'
    else
      render action: "edit"
    end
  end

  def destroy
    @doc_type.is_deleted
    redirect_to doc_types_url
  end

  def get_lines
    @lines = @doc_type.lines
    respond_to do |format|
      format.html { render layout: false}
      format.json { render json: @lines }
    end
  end

  private

  def check_admin!
    redirect_to :back, alert: t('only_admins') and return unless current_user.admin?
  end

  def set_doc_type
    @doc_type = DocType.find(params[:id])
  rescue Mongoid::Errors::DocumentNotFound
  end
  def doc_type_params
    params.require(:doc_type).permit!
  end
end

app/helpers/doc_types_helper.rb
module DocTypesHelper
end

app/views/doc_types/_form.html.haml
= form_for(@doc_type) do |f|
  - @doc_type.errors.messages.delete(:lines)
  - d_l_e_c = @doc_type.lines.map{|dl| dl.errors.count}.sum
  - if @doc_type.errors.any? or d_l_e_c > 0
    #error_explanation
      %h2= t('errors.messages.not_saved', resource: "Тип документа", count: @doc_type.errors.count + d_l_e_c)
      %ul
        - @doc_type.errors.full_messages.each do |msg|
          %li= msg
        - @doc_type.lines.each do |line|
          - line.errors.full_messages.each do |msg|
            %li= msg

  .row
    .form-horizontal
      .form-group
        = f.label :name, nil, class: "col-xs-1 control-label"
        .col-xs-6
          = f.text_field :name, class: "form-control"

  = f.fields_for :lines do |builder|
    = render "line_fields", :f => builder
  %p= link_to_add_fields "Добавить поле", f, :lines
  %hr
  %h4 Шаблон печати типа документа
  .well
    - print_settings_data = DocType::PrintSettingsData
    - print_settings = @doc_type.print_settings
    =@doc_type.print_settings.inspect
    .print_head
      - print_settings_head = print_settings["head"] || {}
      .row
        .form-horizontal
          .form-group
            = label_tag :print_settings_head,"Шапка документа", class: "col-xs-2 control-label"
            .col-xs-6
              - checked = print_settings.blank? || !print_settings["head"].blank?
              = check_box_tag "print_settings[head][head]", "1", checked
          .form-group
            = label_tag :print_settings_head_position, "Расположение:", class: "col-xs-2 control-label"
            .col-xs-6
              = select_tag "print_settings[head][position]", options_for_select(print_settings_data[:head][:positions].collect{|key, value| [value, key]}, print_settings_head["position"])
          .form-group
            = label_tag :print_settings_head_font_size, "Размер шрифта:", class: "col-xs-2 control-label"
            .col-xs-6
              = select_tag "print_settings[head][font_size]", options_for_select(8..18, print_settings_head["font_size"] || 10)
          .form-group
            = label_tag :print_settings_head_case, "Регистр:", class: "col-xs-2 control-label"
            .col-xs-6
              = select_tag "print_settings[head][case]", options_for_select(print_settings_data[:head][:cases].collect{|key, value| [value, key]}, print_settings_head["case"])
          .form-group
            = label_tag :print_settings_head_text, "Текст:", class: "col-xs-2 control-label"
            .col-xs-4
              = text_area_tag "print_settings[head][text]", print_settings_head["text"], {class: "form-control", rows: 5, placeholder: "Текст шапки. Можно использовать %{переменная}"}
      %hr

    .print_title
      - print_settings_title = print_settings["title"] || {}
      .row
        .form-horizontal
          .form-group
            = label_tag :print_settings_title,"Заголовок", class: "col-xs-2 control-label"
            .col-xs-6
              - checked = print_settings.blank? || !print_settings["title"].blank?
              = check_box_tag "print_settings[title][title]", "1", checked
          .form-group
            = label_tag :print_settings_title_font_size, "Размер шрифта:", class: "col-xs-2 control-label"
            .col-xs-6
              = select_tag "print_settings[title][font_size]", options_for_select(8..18, print_settings_title["font_size"] || 12)
          .form-group
            = label_tag :print_settings_title_case, "Регистр:", class: "col-xs-2 control-label"
            .col-xs-6
              = select_tag "print_settings[title][case]", options_for_select(print_settings_data[:title][:cases].collect{|key, value| [value, key]}, print_settings_title["case"])
          .form-group
            = label_tag :print_settings_title_text, "Текст:", class: "col-xs-2 control-label"
            .col-xs-7
              = text_area_tag "print_settings[title][text]", print_settings_title["text"], {class: "form-control", rows: 1, placeholder: "Текст заголовка. Можно использовать %{переменная}"}
      %hr

    .print_body
      - print_settings_body = print_settings["body"] || {}
      .row
        .form-horizontal
          .form-group
            = label_tag :print_settings_body,"Содержимое документа", class: "col-xs-2 control-label"
            .col-xs-6
              - checked = print_settings.blank? || !print_settings_body.blank?
              = check_box_tag "print_settings[body][body]", "1", checked
          .form-group
            = label_tag :print_settings_body_font_size, "Размер шрифта:", class: "col-xs-2 control-label"
            .col-xs-6
              = select_tag "print_settings[body][font_size]", options_for_select(8..18, print_settings_body["font_size"] || 10)
          .form-group
            = label_tag :print_settings_body_case, "Регистр:", class: "col-xs-2 control-label"
            .col-xs-6
              = select_tag "print_settings[body][case]", options_for_select(print_settings_data[:body][:cases].collect{|key, value| [value, key]}, print_settings_body["position"])
          .form-group
            = label_tag :print_settings_body_text, "Текст:", class: "col-xs-2 control-label"
            .col-xs-9
              = text_area_tag "print_settings[body][text]", print_settings_body["text"], {class: "form-control", rows: 20, placeholder: "Текст документа. Можно использовать %{переменная}"}
      %hr



  .actions
    = f.submit t("save"), class: 'btn btn-success'

app/views/doc_types/_line_fields.html.haml
.field.well.well-sm
  = f.hidden_field(:_destroy) + link_to_function(raw("<span class='glyphicon glyphicon-remove pull-right' title = #{"Удалить поле"}></span>"), "remove_fields(this)")
  .form-group.col-xs-9
    = f.text_field :name, placeholder: 'Название поля', class: 'form-control col-lg-6'
  = f.select :type, options_for_select(Line::Defines::FIELD_TYPES.map{|type, name| [name, type]}, :selected => f.object.type), class: 'col-lg-6 form-control'
  = f.text_area :title, rows: 2, class: "form-control", placeholder: "Краткое описание назначения поля"

app/views/doc_types/edit.html.haml
%h1= t(".title")
= render 'form'

app/views/doc_types/get_lines.html.haml
- @lines.each do |line|
  - icon_class, input_class = (line.type == "date" ? ["calendar", "datepicker"] : ["question-sign", ""])
  - field_options = {class: "form-control", :disabled => true, title: "Чтобы редактировать поле нужно сохранить документ"}
  - name = nil #= "lines[#{line.id}]"
  .form-group.col-xs-9
    = label_tag line.name, nil, class: "col-xs-3 control-label"
    .col-xs-6
      .input-group{class: input_class}
        -case line.type
        -when "date"
          = text_field_tag name, nil, field_options
        -when "boolean"
          = check_box_tag name, "1", false, field_options
        -when "integer"
          = number_field_tag name, nil, field_options
        -when "string"
          = text_field_tag name, nil, field_options
        -else
          = text_field_tag name, nil, field_options

        %span.input-group-addon{title: (line.title.blank? ? "Описание поля отсутствует" : line.title) + "\n(#{line.human_type})"}
          %span{class: "glyphicon glyphicon-#{icon_class}"}

app/views/doc_types/index.html.haml
%h2= t(".title")
%table.table.table-hover
  %tr
    %th= t("doc_types.name")
    %th= t("action")
  - @doc_types.each do |doc_type|
    %tr
      %td
        = doc_type.name
      %td.col-md-2
        .btn-group
          = link_to t("show"), doc_type, class: "btn btn-primary"
          %button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li= link_to t("edit"), edit_doc_type_path(doc_type)
            %li.divider
            %li= link_to t("destroy"), doc_type, method: :delete, data: { confirm: t("confirm") }
= link_to new_doc_type_path, class: "btn btn-success" do
  %span.glyphicon.glyphicon-folder-open
  = t("doc_types.new_doc_type")

app/views/doc_types/new.html.haml
= link_to doc_types_path do
  %span.glyphicon.glyphicon-arrow-left
  = t("back")

%h2= t(".title")
%hr
= render 'form'

app/views/doc_types/show.html.haml
%h1= t(".title")
.form-group.col-xs-9
  .col-xs-3
    %b= t("doc_types.name")
  .col-xs-6 
    = @doc_type.name
.clearfix    
-@doc_type.lines.each do |line|  
  .well.well-sm.form-group.col-xs-9  
    .col-xs-3= line.name
    .col-xs-6= line.human_type
.clearfix
= link_to t("edit"), edit_doc_type_path(@doc_type), class: "btn btn-primary"
= link_to t("back"), doc_types_path, class: "btn btn-primary"