config/routes.rb
VDocFlow::Application.routes.draw do
  resources :chat_rooms do
    member do
      post :post_message
      get :leave
    end
  end

  resources :docs do
    member do
      post :change_responsible
      post :to_review
      post :reject
      post :to_revision
      post :accept
      post :to_execution
      post :to_confirmation_of_execution
      post :to_executed
      get :create_chat_room
      get :print
    end
  end

  resources :doc_types do
    member do
      get 'get_lines'
    end
  end

  devise_for :users

  resources :users do
    member do
      get 'toggle_status'
    end
  end

  root :to => 'docs#index'

end

app/models/user.rb
class User
  include Mongoid::Document


  module Defines
    ROLES = {
    	"dep_head" => "Начальник отдела", "deputy_head" => "Зам. начальника отдела",
    	"group_head" => "Начальник группы", "engineer" => "Инженер",
    	"secretary" => "Секретарь", "admin" => "Администратор"
    }

    STATUSES = {
      "not_activated" => "Не активирован",
      "enabled" => "Активен", "disabled" => "Заблокирован",
      "deleted" => "Удален"
    }
  end

  scope :admins, ->  { where(:role => "admin").order_by(:name => 1) }
  scope :simple_users, -> { where(:role.ne => "admin").order_by(:name => 1) }
  scope :enabled, -> { where(:status => "enabled").order_by(:name => 1) }
  scope :exists, -> { where(:status.ne => "deleted").order_by(:name => 1) }
  scope :deleted, -> { where(:status => "deleted").order_by(:name => 1) }

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  field :name, type: String
  # field :post, type: String
  field :role, type: String
  field :status, type: String, default: "not_activated"
  has_many :docs
  has_many :message_notifications
  has_many :doc_notifications
  has_many :doc_change_notifications

  validates_presence_of :name
  validates_uniqueness_of :name, case_sensitive: false

  def admin?
    role == "admin"
  end

  def enabled?
    status == "enabled"
  end

  # def human_post
  # 	# POSTS[post] || "UNDEFINED"
  # 	"POSTS UNDEFINED"
  # end

  def human_role
    Defines::ROLES[role] || "Роль #{role} неопределена!"
  end

  def human_status
  	Defines::STATUSES[status] || "Статус #{status} неопределен!"
  end

  def alt_attrs
    {"id" => self.id.to_s, "name" => self.name}
  end
end

app/controllers/users_controller.rb
require 'securerandom'
class UsersController < ApplicationController
  before_filter :set_user, only: [:show, :edit, :update, :toggle_status, :destroy]
  before_filter :check_admin!, except: [:index, :show]
  before_filter :check_access!, only: [:edit, :update]

  def index
    respond_to do |format|
      format.html do
        check_admin!
        @users = User.all
      end
      format.json do
        q = params[:q] || ""
        @users = User.where(name: /.*#{q.mb_chars.downcase.to_s}.*/i)
        render :json => @users.map(&:alt_attrs)
      end
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    p = SecureRandom.urlsafe_base64(10) #like "v_2avsdlnN2a7w"
    @user.password = p
    if @user.save
      redirect_to @user, notice: "Пользователь успешно создан.<br>Пароль пользователя <strong>'#{p}'</strong> (без кавычек)".html_safe
    else
      render action: "new"
    end
  end

  def update

    password_changed = !params[:user][:password].blank?
    success =
    if password_changed
      password_ok = (params[:user][:password] == params[:user][:password_confirmation])
      if password_ok
        @user.password = params[:user][:password]
        @user.update_without_password(params_for_update)
      else
        flash[:alert] = t(".passwords_not_equal")
        @user.assign_attributes(params_for_update_with_password)
        false
      end
    else
      @user.update_without_password(params_for_update)
    end


    if success #@user.update_attributes(user_params)
      redirect_to @user, notice: 'Пользователь успешно обновлен'
    else
      render action: "edit"
    end
  end

  def toggle_status
    if params[:s] == '0'
      status = "disabled"
    elsif params[:s] == '1'
      status = "enabled"
    else
      redirect_to :back, alert: "Некорректный параметр для смены статуса!" and return
    end
    @user.status = status
    @user.save!
    redirect_to :back, notice: "Статус пользователя изменен!"
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  protected

  def check_admin!
    redirect_to docs_path, alert: t('only_admins') and return unless current_user.admin?
  end

  def check_access!
    redirect_to docs_path, alert: 'Only owner or admins allowed!' and return unless (current_user.id == @user.id or current_user.admin?)
  end

  private

  def params_for_update_with_password(*additional_keys)
    params_for_update(:password, :password_confirmation, *additional_keys)
  end

  def params_for_update(*additional_keys)
    params.require(:user).permit(:email, :name, :role, *additional_keys)
  end

  def set_user
    @user = User.find(params[:id])
  rescue Mongoid::Errors::DocumentNotFound
  end

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .form-group.col-xs-9
    = f.label t("users.name"), {class: "col-xs-3 control-label"}
    .col-xs-6
      = f.text_field :name, {class: "form-control col-xs-5"}

  .form-group.col-xs-9
    = f.label t("users.email"), {class: "col-xs-3 control-label"}
    .col-xs-6
      = f.email_field :email, {class: "form-control"}

  .form-group.col-xs-9
    = f.label t("users.role"), {class: "col-xs-3 control-label"}
    .col-xs-6
      = f.select :role, options_for_select(User::Defines::ROLES.map{|role, name| [name, role]}, selected: @user.try(:role)), {class: "form-control"}, :'data-width' => '100%'

  .form-group.col-xs-9
    = f.label(:password, {class: "col-xs-3 control-label"})
    .col-xs-6
      = f.password_field(:password, {class: "form-control", autocomplete: 'off'})

  .form-group.col-xs-9
    = f.label(:password_confirmation, {class: "col-xs-3 control-label"})
    .col-xs-6
      = f.password_field(:password_confirmation, {class: "form-control"})

  .clearfix

  .actions
    = f.submit t("save"), class: 'btn btn-success'

app/views/users/edit.html.haml
%h2= t(".title")
%hr
= render 'form'

app/views/users/index.html.haml
%h2= t(".title")
%br
%table.table.table-hover
  %tr
    %th= t("users.name")
    %th= t("users.role")
    %th= t("users.status")
    %th= t("action")
  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.human_role
      %td= user.human_status
      %td.col-md-2
        .btn-group
          = link_to t("show"), user, class: "btn btn-default"
          %button.btn.btn-success.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li= link_to t("edit"), edit_user_path(user)
            %li
              -if user.enabled?
                = link_to t("disable"), toggle_status_user_path(user, s: 0)
              -else
                = link_to t("enable"), toggle_status_user_path(user, s: 1)
            %li
            %li.divider
            %li= link_to t("destroy"), user, method: :delete, data: { confirm: t("confirm") }
= link_to new_user_path, class: "btn btn-success" do
  %span.glyphicon.glyphicon-user
  = t("users.new_user")

app/views/users/new.html.haml
= link_to users_path do
  %span.glyphicon.glyphicon-arrow-left
  = t("back")

%h2= t(".title")
%hr
= render 'form'

app/views/users/show.html.haml
= link_to users_path do
  %span.glyphicon.glyphicon-arrow-left
  = t("back")

%h2
  = t(".title")
%hr
.well
  %p
    %b= t("users.name")
    = @user.name
  %p
    %b= t("users.email")
    = @user.email
  %p
    %b= t("users.role")
    = @user.human_role
  %p
    %b= t("users.status")
    = @user.status

= link_to edit_user_path(@user), class: "btn btn-warning" do
  %span.glyphicon.glyphicon-edit
  = t("edit")