config/routes.rb
VDocFlow::Application.routes.draw do
  resources :chat_rooms do
    member do
      post :post_message
      get :leave
    end
  end

  resources :docs do
    member do
      post :change_responsible
      post :to_review
      post :reject
      post :to_revision
      post :accept
      post :to_execution
      post :to_confirmation_of_execution
      post :to_executed
      get :create_chat_room
      get :print
    end
  end

  resources :doc_types do
    member do
      get 'get_lines'
    end
  end

  devise_for :users

  resources :users do
    member do
      get 'toggle_status'
    end
  end

  root :to => 'docs#index'

end

app/views/layouts/_bootstrap_flash.html.haml
-flash.each do |type, message|
  -next if message.blank?
  -type = :success if type == :notice
  -type = :danger   if type == :alert
  -Array(message).each do |msg|
    %div{class: "alert fade in alert-#{type}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
      = msg

app/views/layouts/_topbar.html.haml
.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "/"}= t('app_title')
    .collapse.navbar-collapse.navbar-collapse
      -if user_signed_in?
        %ul.nav.navbar-nav
          - if current_user.admin?
            %li
              = link_to users_path do
                %span.glyphicon.glyphicon-user
                = t('.users')
          %li
            = link_to doc_types_path do
              %span.glyphicon.glyphicon-list
              = t('.doc_types')
          %li
            = link_to docs_path do
              %span.glyphicon.glyphicon-file
              = t('.docs')
              - unless current_user.doc_notifications.blank?
                = current_user.doc_notifications.count + current_user.doc_change_notifications.count

        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to chat_rooms_path do
              - unless current_user.message_notifications.blank?
                %span.glyphicon.glyphicon-envelope.text-primary
                  = current_user.message_notifications.count

              - else
                %span.glyphicon.glyphicon-envelope

          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              %span.glyphicon.glyphicon-user
              = current_user.name
              %b.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to(current_user) do
                  %span.glyphicon.glyphicon-cog
                  = t('.profile')
              %li.divider
              %li
                = link_to(destroy_user_session_path, :method => :delete) do
                  %span.glyphicon.glyphicon-log-out
                  = t('.logout')
      -else
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to(new_user_session_path) do
              %span.glyphicon.glyphicon-log-out
              = t('.login')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %title
      = t('page_title', :scope => @page_scope)
    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags
  %body.application-layout
    .wrapper
      =render 'layouts/topbar'
      %section.content.container
        = render partial: "layouts/bootstrap_flash", locals: {flash: flash}
        = yield
    = javascript_include_tag "application"

    /= stylesheet_link_tag "application", "token-input-facebook"
    /= javascript_include_tag :defaults, "jquery.tokeninput"

app/views/layouts/get_lines.haml
!!!
%html
  %head
    = javascript_include_tag "application"
    = yield